### ISSUE TITLE
windows log路径问题

### ISSUE THREAD

**Issue by cool3rzZ** [lyhue1991/eat_tensorflow2_in_30_days#14]
如果在windows上使用绝对路径时，需要写成类似
logdir = 'C:\\xx\\autograph\\%s' %stamp

**Comment by lyhue1991** [comment]
感谢 @cool3rzZ 反馈，已经修改。⭐️

**Comment by cool3rzZ** [comment]
抱歉，之前可能复制有误，路径应该是'C:\\xx\\autograph\\%s' %stamp，

**Comment by nbwuzhe** [comment]
@cool3rzZ 已经进一步修复，应该能兼容多种操作系统了(我自己用windows测试没问题)。请git pull origin master使用最新版本呢。如果还是有问题还请继续告诉大家哈。
