### ISSUE TITLE
1-1结构化数据建模流程规范的问题

### ISSUE THREAD

**Issue by Tokkiu** [lyhue1991/eat_tensorflow2_in_30_days#15]
在1-1章中， 作者使用到的`y_test = dftest_raw['Survived'].values`，其中dftest_raw是没有`Survived`这一列的， 这个时候会报错。

不知道作者使用的test data是官方的test data，还是从train data中分割一部分出来成为test data呢？ 谢谢！

**Comment by sevenold** [comment]
你可以dftest_raw.head()看看你的数据里有没有Survived字段，或者直接用作者提供的数据。

**Comment by Tokkiu** [comment]
谢谢你的回复 @sevenold  我看了一下 的确作者提供的数据和titanic的原始数据不一样 ，可能是作者预处理过了。我按照作者源代码中的路径去下载csv文件，问题得到解决。

**Comment by Tokkiu** [comment]
但是作者这么做的原因是为什么呢？ 我可以理解为作者做了一个打乱数据的行为， 而且把原始数据中的train data分割成了两部分， 一部分是train data， 一部分是test data（cross validation data）吗？ 谢谢！

**Comment by lyhue1991** [comment]
是把原始数据的训练集拆分成两部分的，目的是为了构造有标签的验证集。
