### ISSUE TITLE
同步到 github.io 的延迟

### ISSUE THREAD

**Issue by LucienShui** [lyhue1991/eat_tensorflow2_in_30_days#20]
今天我发现 [3-1,低阶API示范](https://lyhue1991.github.io/eat_tensorflow2_in_30_days/3-1,%E4%BD%8E%E9%98%B6API%E7%A4%BA%E8%8C%83.html) 和 [eat_tensorflow2_in_30_days/3-1,低阶API示范.md](https://github.com/lyhue1991/eat_tensorflow2_in_30_days/blob/master/3-1%2C%E4%BD%8E%E9%98%B6API%E7%A4%BA%E8%8C%83.md) 的内容不一样，猜测应该是因为同步过去有延迟，想了解一下同步过去需要多久？

**Comment by lyhue1991** [comment]
感谢反馈。🍉 不是延迟呢，是因为gitbook电子书对应的branch源码还没有更新。后续等修改相对稳定后会更新gitbook电子书的哦。

**Comment by LucienShui** [comment]
好的，🙏非常感谢。
