### ISSUE TITLE
1-2预处理num_parallel_calls出现问题

### ISSUE THREAD

**Issue by LucasDurian** [lyhue1991/eat_tensorflow2_in_30_days#22]
Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

**Comment by lyhue1991** [comment]
应该是版本的问题。
