### ISSUE TITLE
1-2 load_image函数打标签错误

### ISSUE THREAD

**Issue by Josephine621** [lyhue1991/eat_tensorflow2_in_30_days#23]
![image](https://user-images.githubusercontent.com/55381998/79407314-c5b0ac00-7fcb-11ea-8546-54e90495fbf1.png
标签全为0，导致后续训练正确率均为1.
Train for 100 steps, validate for 20 steps
Epoch 1/10
100/100 [==============================] - 16s 162ms/step - loss: 0.0116 - accuracy: 0.9904 - val_loss: 1.2626e-09 - val_accuracy: 1.0000
Epoch 2/10
100/100 [==============================] - 11s 106ms/step - loss: 5.7853e-09 - accuracy: 1.0000 - val_loss: 1.2602e-09 - val_accuracy: 1.0000
Epoch 3/10
100/100 [==============================] - 11s 105ms/step - loss: 5.7422e-09 - accuracy: 1.0000 - val_loss: 1.2595e-09 - val_accuracy: 1.0000
...

**Comment by lyhue1991** [comment]
请下载最新的代码呢，这个问题是windows下路径格式的问题，已经兼容了。

**Comment by Josephine621** [comment]
Thank you~
