### ISSUE TITLE
estimator是否考虑加入书籍？

### ISSUE THREAD

**Issue by weberrr** [lyhue1991/eat_tensorflow2_in_30_days#26]
estimator是tf从1到2一直延续的重要api，层级上来看应该属于高阶api，可以直接定义model。
是否考虑把这一部分加入书籍呢？
为什么把这部分丢弃，是出于什么考虑呢

**Comment by lyhue1991** [comment]
@weberrr  感谢建议。estimator在2中已经处于维护状态了呢，不会添加新的支持特性，官方现在唯一推荐的高阶API是keras.

**Comment by weberrr** [comment]
@lyhue1991 感谢您的回复和解答。您的tf2的内容是我看过最为清晰的。是否考虑也出tf1.x系列的内容呢？一方面是官方的tf1.x的文档非常不好，并且由于官方文档的下架（替换为tf2，仅保留tf1.x的api的github地址），相关的文档非常之少，且非常不清晰；另一方面是工业界普遍还是在使用tf1.x（既有迭代慢的原因，也有效果比tf2好的原因），出tf1.x非常有指导意义。

**Comment by lyhue1991** [comment]
@weberrr  感谢建议呢。认清形势，放弃幻想。早日拥抱tf2吧
