### ISSUE TITLE
3-1 低阶API示范 构建数据管道迭代器

### ISSUE THREAD

**Issue by mc0514** [lyhue1991/eat_tensorflow2_in_30_days#32]
3-1 低阶API示范 构建数据管道迭代器data_iter(features, labels, batch_size=8)函数中，
yield tf.gather(X,indexs), tf.gather(Y,indexs)
是不是该写成
tf.gather(features,indexs), tf.gather(labels,indexs)

**Comment by nbwuzhe** [comment]
@lyhue1991 我也觉得这块有疑问，argument在函数中没有使用。麻烦确认下哈。

**Comment by lyhue1991** [comment]
done!
