### ISSUE TITLE
3-2在GPU上运行会报错，查了一下发现有人在CPU下可以运行

### ISSUE THREAD

**Issue by since2016** [lyhue1991/eat_tensorflow2_in_30_days#33]
会报错如下
``  (0) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: class tensorflow::data::`anonymous namespace'::DatasetVariantWrapper
	 [[{{node while_input_4/_12}}]]
  (1) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: class tensorflow::data::`anonymous namespace'::DatasetVariantWrapper
	 [[{{node while_input_4/_12}}]]
	 [[Func/while/body/_1/input/_60/_20]]``

**Comment by nbwuzhe** [comment]
我记得这个是training的时候报的错吧？如果是的话，请更新到最新的代码就解决这个问题了。我在GPU下测试过是没问题的。

**Comment by since2016** [comment]
> 
> 
> 我记得这个是training的时候报的错吧？如果是的话，请更新到最新的代码就解决这个问题了。我在GPU下测试过是没问题的。

发现文档更新了，感谢提醒。
