### ISSUE TITLE
spark-scala调用tensorflow2.0 模型会报错

### ISSUE THREAD

**Issue by boluoyu** [lyhue1991/eat_tensorflow2_in_30_days#4]
有个疑问，原生SavedModelBundle 、Session 类并没有实现serializable 接口，直接 

`
val broads = sc.broadcast(bundle)`
会报
`Serialization stack:
	- object not serializable (class: org.tensorflow.SavedModelBundle, value: org.tensorflow.SavedModelBundle@6a1ebcff)`

的异常，自己要修改原码增加 serializable 接口，要改不少代码，文中是如何做到这点的呢？

**Comment by lyhue1991** [comment]
提交spark任务时需要加入以下配置
```bash
--conf spark.serializer=org.apache.spark.serializer.KryoSerializer 

--conf spark.kryo.referenceTracking=true 
```

**Comment by boluoyu** [comment]
@lyhue1991  这个没有用吧，KryoSerializer 本身要求是要实现这个接口才行，SavedModelBundle 本身没有实现这个接口，即使加上了这些配置一样会报错，不知道作者是怎么做到，能否贴出来所有代码出来参考一下？

**Comment by lyhue1991** [comment]
项目中就是全部代码呢。没有任何隐瞒。

你对KryoSerializer 的作用方式的理解可能和我有些不同。我理解它的作用是用来替代java自带的序列化方法的。--conf spark.kryo.referenceTracking=true  由于我们加了这条配置，而我们的主object有 extends Serializable这个声明，所以object下所有的变量和方法都会继承这个序列化特征。

**Comment by ifeela** [comment]
测试过  可以用    
   val bundle = tf.SavedModelBundle.load(
      "/Users/carol/dev/java/voiceTag/src/main/resources/models/gender_2_0.96",
      "serve"
    )
    val conf = new SparkConf().setMaster("local").setAppName("TfRDD")
              .set("spark.executor.memory", "2g")
              .set("spark.executor.cores", "2")
              .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
              .set("spark.kryo.referenceTracking", "true")

    val spark = SparkSession.builder().config(conf=conf).enableHiveSupport().getOrCreate()

    val sc = spark.sparkContext
    val broads = sc.broadcast(bundle)

    val sess = broads.value.session()
    val x = tf.Tensor.create(arr)
    val y =  sess.runner().feed("serving_default_inputs:0", x)
      .fetch("StatefulPartitionedCall:0").run().get(0)

    val result = Array.ofDim[Float](y.shape()(0).toInt,y.shape()(1).toInt)
    y.copyTo(result)

**Comment by boluoyu** [comment]
@ifeela 多谢了，可以跑，之前设置 conf 有问题导致的

**Comment by shuaidan0412** [comment]
最后在集群上跑成功了么

**Comment by boluoyu** [comment]
> 最后在集群上跑成功了么

成功了

**Comment by myelinji** [comment]
模型文件能放到集群吗？这个是不是只能本地加载模型文件？

**Comment by 16pk** [comment]
我在local模式下能够执行代码，但是在yarn-client或cluster模式下都会报java.lang.NoClassDefFoundError: Could not initialize class org.tensorflow.SavedModelBundle错误

**Comment by boluoyu** [comment]
> 
@myelinji  模型文件需要下载到临时目录进行加载

**Comment by mokundong** [comment]
local 模式下了能跑成功，在yarn cluster模式下，session.run() 会线程阻塞
