### ISSUE TITLE
张量的数学运算中矩阵特征值演示错误

### ISSUE THREAD

**Issue by lynquantumman** [lyhue1991/eat_tensorflow2_in_30_days#42]
#矩阵特征值
tf.linalg.eigvalsh(a) 是self-adjoint matrix 的特征值， 而不是一般矩阵的矩阵特征值

**Comment by nbwuzhe** [comment]
@lyhue1991 I agree, the tf.linalg.eigvals(a) should be used instead of tf.linalg.eigvalsh(a). What do you think?

**Comment by lyhue1991** [comment]
@lynquantumman @nbwuzhe  Thank you very much, The error has been fixed!
