### ISSUE TITLE
Some Suggestions for '1-3' Maybe

### ISSUE THREAD

**Issue by LEON-REIN** [lyhue1991/eat_tensorflow2_in_30_days#47]
# Excuse me. QAQ But I hope to get suggestions!
-----
## Where the issue happens
Chapter `1-3,文本数据建模流程范例`
```python
# 构建词典
def clean_text(text):
    ...
    tf.strings.regex_replace(stripped_html,
         '[%s]' % re.escape(string.punctuation),'')
```

## Issue Detail
In `re.escape(string.punctuation),''`, should `''` be this->`' '` ?
Otherwise, we'll get "himbut" from "him,but".
Additionally, I'm considering we should remove "'" from `string.punctuation`.
Otherwise, we'll get "It's a good" from "it s a good".

## My Edition for These Codes
```python
def clean_text(text):
    # A string include all punctuations which has been escaped by re.
    # Use '\\' for escape of metacharacters.
    escaped_punctuation = re.escape(string.punctuation.replace("'", ""))
    lowercase = tf.strings.lower(text)
    stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
    cleaned_punctuation = tf.strings.regex_replace(stripped_html,
                                                   '[%s]' % escaped_punctuation, ' ')

    return cleaned_punctuation
```

**Comment by lyhue1991** [comment]
Thanks for your suggestions very much.   @LEON-REIN You  considered some details in cleanning the text data. Actually the details of text cleanning method is not that important in the whole preprocessing procedure. And in many cases, the punctuations will come together with a  blank in the text. As in your example, "him,but" often comes like "him, but". So we may not to replace the punctuations by a blank in the preprocessing procedure. Also, a complex text cleanning procedure will make the readers puzzled。

**Comment by LEON-REIN** [comment]
I got it! 
: )
