### ISSUE TITLE
文件路径表示问题

### ISSUE THREAD

**Issue by yuanxiaosc** [lyhue1991/eat_tensorflow2_in_30_days#6]
由于Windows和类Unix系统对于路径表示有差异，所以示例代码需要考虑兼容性才能在不同系统成功运行。以“1-2,图片数据建模流程范例”为例子，其中tf.strings.regex_full_match(img_path, ".*/automobile/.*")就需要改为tf.strings.regex_full_match(img_path, ".*automobile.*")，以及logdir = "./data/keras_model/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")也需要改为用os.path.join()函数连接的形式而不是硬编码。

**Comment by lyhue1991** [comment]
很好的建议，我周末抽时间调一下修改一下。感谢烙铁 @yuanxiaosc
