### ISSUE TITLE
tensoflow

### ISSUE THREAD

**Issue by jaovc** [lyhue1991/eat_tensorflow2_in_30_days#67]

**Comment by ChaplinPig** [comment]
View it on Github

发送自 Windows 10 版邮件应用

发件人: jaovc
发送时间: 2020年9月18日 4:58
收件人: lyhue1991/eat_tensorflow2_in_30_days
抄送: Subscribed
主题: [lyhue1991/eat_tensorflow2_in_30_days] tensoflow (#67)
