### ISSUE TITLE
Day 2 知乎链接失效

### ISSUE THREAD

**Issue by Ahacad** [lyhue1991/eat_tensorflow2_in_30_days#68]
https://zhuanlan.zhihu.com/p/67466552 
链接 404

**Comment by nbwuzhe** [comment]
@lyhue1991 I can't find the archiving version, could you provide an alternative?

**Comment by erikalien5595** [comment]
I met the same problem, could you provide an alternative, plz?

**Comment by lyhue1991** [comment]
> @lyhue1991 I can't find the archiving version, could you provide an alternative?

this problem has been fixed
