### ISSUE TITLE
1-3的Valid Loss为什么在上升？

### ISSUE THREAD

**Issue by yzho0907** [lyhue1991/eat_tensorflow2_in_30_days#69]
源文档中：
Epoch=1,Loss:0.442317516,Accuracy:0.7695,Valid Loss:0.323672801,Valid Accuracy:0.8614
Epoch=2,Loss:0.245737702,Accuracy:0.90215,Valid Loss:0.356488883,Valid Accuracy:0.8554
Epoch=3,Loss:0.17360799,Accuracy:0.93455,Valid Loss:0.361132562,Valid Accuracy:0.8674
Epoch=4,Loss:0.113476314,Accuracy:0.95975,Valid Loss:0.483677238,Valid Accuracy:0.856
Epoch=5,Loss:0.0698405355,Accuracy:0.9768,Valid Loss:0.607856631,Valid Accuracy:0.857
Epoch=6,Loss:0.0366807655,Accuracy:0.98825,Valid Loss:0.745884955,Valid Accuracy:0.854

我复现后：
Epoch=1,Loss:0.679053724,Accuracy:0.55235,Valid Loss:0.572207093,Valid Accuracy:0.717
Epoch=2,Loss:0.467248648,Accuracy:0.7762,Valid Loss:0.491477,Valid Accuracy:0.7588
Epoch=3,Loss:0.349681437,Accuracy:0.8475,Valid Loss:0.514342368,Valid Accuracy:0.7628
Epoch=4,Loss:0.278649092,Accuracy:0.8863,Valid Loss:0.564446032,Valid Accuracy:0.763
Epoch=5,Loss:0.2197005,Accuracy:0.9159,Valid Loss:0.643948495,Valid Accuracy:0.7548
Epoch=6,Loss:0.163983703,Accuracy:0.94135,Valid Loss:0.770707726,Valid Accuracy:0.7524

可以看到Valid Loss在逐渐上升

**Comment by xinxilwl** [comment]
过拟合

**Comment by yzho0907** [comment]
> 过拟合

有可能是，感谢
