### ISSUE TITLE
请问作者考虑写一下tft data pipeline内容吗？

### ISSUE THREAD

**Issue by neilteng** [lyhue1991/eat_tensorflow2_in_30_days#7]
tf2 加入了tfx的扩展支持，其中tfr我觉得是最可能在工程中用到。请问作者考虑加入这部分的教程？

典型的一个场景是：
里面对apache beam的整合，可以让我们将线下训练和线上serving的data pipeline统一起来。这样子我们的model只要消费pipeline给的数据就好了。

**Comment by lyhue1991** [comment]
@neilteng 感谢提供建议，不过tfx这一块我并不是很了解。工作中暂时还没有涉及到呢。目前这个教程还是偏向基础常用的用法 😬
