### ISSUE TITLE
在6-3章节我遇到有一个小错误

### ISSUE THREAD

**Issue by barrylee9527** [lyhue1991/eat_tensorflow2_in_30_days#8]
6-3里面有一句gpus = tf.config.list_physical_devices("GPU")
我在运行之后会报错，module 'tensorflow_core._api.v2.config' has no attribute 'list_physical_devices'
我改为tf.config.experimental.list_physical_devices("GPU")解决了，不知道其他人遇没遇见，建议可以修改一下。

**Comment by lyhue1991** [comment]
@barrylee9527 感谢提醒，我又确认了一下，在 2.1以后的版本是可以不加experimental的呢
