### ISSUE TITLE
1-4部分说法似乎欠妥当

### ISSUE THREAD

**Issue by maxinwx** [lyhue1991/eat_tensorflow2_in_30_days#85]
感谢作者的辛勤劳动，给英语吃力的我造福了。
中文版１-4节中开始说“国内的新冠肺炎疫情从发现至今已经持续3个多月了，这场起源于吃野味的灾难给大家的生活造成了诸多方面的影响”个人感觉欠妥当。硬着头皮去看了下英文版的，不知道是英文版已经改了还是原本就没有，疫情产生的原因英文版并没有说。事实上，都２０２１年了，世界各国的科学家还在寻找病毒的来源，并没有一个定论。个人感觉这个说法似乎不太好，不需要为了活跃气氛加上过多东西。

**Comment by nbwuzhe** [comment]
有几点需要注意：
1. 本repo是先有中文版，再有英文版，很显然你没有查看commit记录。
2. 原作者完成中文版时的报道就是这样（再次说明你没有查看commit的记录）。用现在的标准去否定过去已经发生的事情，是典型的历史虚无主义。
3. 希望读者们能多关注技术层面的问题，对技术相关问题咬文嚼字是很欢迎的。
