### ISSUE TITLE
Is there english version?

### ISSUE THREAD

**Issue by xTunqki** [lyhue1991/eat_tensorflow2_in_30_days#9]

**Comment by lyhue1991** [comment]
There is not an english version yet.  But we may provide an english version branch later.

**Comment by nbwuzhe** [comment]
Working on it

**Comment by xTunqki** [comment]
thank you

**Comment by nbwuzhe** [comment]
English version is completed (except the epilogue) but is still under review. We really appreciate your feedback for any mistake, inaccurate or ambiguous expressions.
